
if (EXISTS "${CMAKE_CURRENT_LIST_DIR}/NRD/CMakeLists.txt")
	set(NRD_DXC_PATH ${DXC_PATH})
	set(NRD_DXC_SPIRV_PATH ${DXC_SPIRV_PATH})
	set (NRD_NORMAL_ENCODING "0" CACHE STRING "")
	set (NRD_ROUGHNESS_ENCODING "1" CACHE STRING "")
	set (GLOBAL_BIN_OUTPUT_PATH "${CMAKE_CURRENT_BINARY_DIR}" CACHE STRING "")
	set (NRD_SHADERS_PATH "${CMAKE_CURRENT_BINARY_DIR}/NRD_Shaders" CACHE STRING "")
	option(NRD_STATIC_LIBRARY "" ON)

	add_subdirectory(NRD)
	
	set_target_properties(NRD PROPERTIES FOLDER NRD)
	set_target_properties(NRD_Shaders PROPERTIES FOLDER NRD)
endif()
